services:
  nextjs-chat-rag:
    container_name: nextjs-chat-rag
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - 3000:3000
    entrypoint: sh -c "pnpm install && pnpm run build && pnpm run dev"
    working_dir: /nextjs-chat-rag
    volumes:
      - .:/nextjs-chat-rag
